name: discord_gpt_4
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest bandit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Display environment variables
        run: |
          echo "MAIN_CHANNEL_ID: $MAIN_CHANNEL_ID"
          echo "ADMIN_SECRET: $ADMIN_SECRET"
          echo "DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN"
          echo "DISCORD_CLIENT_ID: $DISCORD_CLIENT_ID"
          echo "OPENAI_API_KEY: $OPENAI_API_KEY"
      - name: Run tests
        run: |
          python -m pytest tests/
      - name: Run Bandit security checks
        run: |
          bandit -r ./ -ll -ii -x B101
